name: Continuous integration
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stepchowfun/toast/.github/actions/toast@master
      with:
        tasks: build
    - uses: JamesIves/github-pages-deploy-action@4.1.0
      if: github.ref == 'refs/heads/master'
      with:
        branch: gh-pages
        folder: dist
