name: CI

on:
  push:
    branches:
    - main
  pull_request:
  # Trigger a build every month to ensure the Instagram token is up-to-date.
  schedule:
  - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      if: github.event_name == 'push'
      with:
        username: juliahw
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: stepchowfun/toast/.github/actions/toast@main
      with:
        tasks: build
        docker_repo: juliahw/juliaspies
        write_remote_cache: ${{ github.event_name == 'push' }}

    - uses: JamesIves/github-pages-deploy-action@4.1.0
      if: github.ref == 'refs/heads/main'
      with:
        branch: gh-pages
        folder: dist
